version: '3.8'

services:
  customer-statistics-service:
    build: .
    container_name: customer-statistics-service
    ports:
      - "8089:8089"
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge
