spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/customer/**
        - id: worker-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/worker/**
        - id: job-schedule-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/job-schedule/**
        - id: register-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/register/**
        - id: worker-contract-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/worker-contract/**
        - id: job-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/job/**,/api/job-category/**
        - id: customer-contract-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/customer-contract/**
        - id: customer-payment-service
          uri: http://localhost:8088
          predicates:
            - Path=/api/customer-payment/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: "*"