server:
  port: 8089

spring:
  application:
    name: customer-statistics-service
  main:
    allow-bean-definition-overriding: true
  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s
    livereload:
      enabled: true

app:
  customer-service:
    url: http://localhost:8085
  customer-contract-service:
    url: http://localhost:8087
  customer-payment-service:
    url: http://localhost:8088
